						<div class="row 200%">
							<div class="12u">
							<!-- Features -->
									<section class="box features">
										<h2 class="major"><span>Sapasnir Oficinas de Recaudación Municipal</span></h2>
										<div>
											<div class="cuadroDir">
											<div class="cMapas">
												<div id="map-1" class="sMapa"></div></a>
												<h3>DIF, CASA DEL ADULTO MAYOR</h3>
															<p>
																Lerdo de Tejada, Libertad, 54407 Villa Nicolás Romero, Méx.

															</p>
											</div>
											<div class="cMapas">
												<div id="map-2" class="sMapa"></div></a>
												<h3>UBRIS NICOLÁS ROMERO</h3>
															<p>
																Los Pinos 16, Independencia, 54409 Villa Nicolás Romero, Méx.
															</p>
											</div>
											<div class="cMapas">
												<div id="map-3" class="sMapa"></div></a>
												<h3>CLINICA DE LA MUJER</h3>
															<p>
																Luis Donaldo Colosio Villa Nicolás Romero, Estado de México
															</p>
											</div>
											
											</div>
											<!-- <div class="row">
												<div class="12u">
													<ul class="actions">
														<li><a href="#" class="button big">Boton Uno</a></li>
														<li><a href="#" class="button alt big">Boton Dos</a></li>
													</ul>
												</div>
											</div> -->
										</div>
										
									</section>

							</div>
						</div>