			<!-- Nav -->
				<nav id="nav">
					<ul>
						<li class="current"><a href="index.php">Inicio</a></li>
						<li><a href="#">¿Quiénes Somos?</a>
							<ul>
								<li><a href="#">Directorio</a></li>
								<li><a href="organigrama.php">Organigrama</a></li>
							</ul>
						</li>

						<li><a href="#">Trámites y Servicios</a>
							<ul>
								<li><a href="#">Tramites</a></li>
							</ul>
						</li>

						
						<li><a href="http://www.ipomex.org.mx/ipo/portal/nicolasromero.web">Transparencia</a>
							<ul>
								<li><a href="#">Programa Anual de Evaluación</a></li>
							</ul>
						</li>
						<li><a href="#">Contacto</a></li>
					</ul>
				</nav>